// Mock data for DPS Dashboard prototype

import type {
  Experiment,
  Campaign,
  KPIMetric,
  PricingComponent,
  TargetGroup,
} from "./types";

// KPI Metrics for Dashboard
export const kpiMetrics: KPIMetric[] = [
  {
    id: "delivery_fee",
    label: "Average Delivery Fee",
    value: 2.26,
    change: 0.48,
    changeType: "positive",
    prefix: "EUR",
    format: "currency",
  },
  {
    id: "total_orders",
    label: "Total Orders",
    value: 62154,
    change: -2.2,
    changeType: "negative",
    format: "number",
  },
  {
    id: "gmv",
    label: "Gross Merchandise Value (GMV)",
    value: 200638,
    change: 0.48,
    changeType: "positive",
    prefix: "EUR",
    format: "currency",
  },
  {
    id: "afv",
    label: "Average Food Value (AFV)",
    value: 14.06,
    change: -0.06,
    changeType: "negative",
    prefix: "EUR",
    format: "currency",
  },
  {
    id: "cvr",
    label: "Conversion Rate (CVR)",
    value: 60.81,
    change: 1.32,
    changeType: "positive",
    suffix: "%",
    format: "percentage",
  },
];

// Active Experiments for Dashboard
export const activeExperiments: {
  id: string;
  name: string;
  activeDuration: string;
  significance: string;
}[] = [
  {
    id: "AR_20240406_R_B0_O_ElasticityCaba",
    name: "AR_20240406_R_B0_O_ElasticityCaba",
    activeDuration: "28 days",
    significance: "25%",
  },
  {
    id: "AR_20240405_L_D0_P_MOVKiosks",
    name: "AR_20240405_L_D0_P_MOVKiosks",
    activeDuration: "16 days",
    significance: "25%",
  },
  {
    id: "AR_20240306_D_G0_O_BV_SanMiguel",
    name: "AR_20240306_D_G0_O_BV_SanMiguel",
    activeDuration: "9 days",
    significance: "25%",
  },
  {
    id: "CL_20240131_Z_Z0_O_SBF_Tucuman",
    name: "CL_20240131_Z_Z0_O_SBF_Tucuman",
    activeDuration: "5 days",
    significance: "25%",
  },
];

// Active Campaigns for Dashboard
export const activeCampaigns: Campaign[] = [
  {
    id: "PY_DFS0_MOV3499_DRINKS_DMT",
    name: "PY - DFS0/MOV3499 - DRINKS DMT",
    timeLeft: "28 days",
    budgetLeft: "3%",
    status: "active",
  },
  {
    id: "PY_DFS0_MOV2499_ESPECIAL_FIESTAS",
    name: "PY - DFS0/MOV2499 - ESPECIAL FIESTAS",
    timeLeft: "16 days",
    budgetLeft: null,
    status: "active",
  },
  {
    id: "PY_DFS0_DBMOV1299_2499_SBX",
    name: "PY - DFS0/DBMOV1299 a 2499 - SBX",
    timeLeft: "9 days",
    budgetLeft: "28%",
    status: "active",
  },
  {
    id: "PY_DFS0_DBMOV1499_1999_REST_AMBA",
    name: "PY - DFS0/DBMOV1499 a 1999 - REST AMBA",
    timeLeft: "5 days",
    budgetLeft: null,
    status: "active",
  },
];

// Experiments list for Experiments page
// IDs are random 3-4 digit numbers that correlate with creation date (higher ID = more recent)
// Balanced distribution: ~10 running, ~10 completed, ~10 draft
export const experiments: Experiment[] = [
  // Oldest experiments (May-July 2023) - IDs: 102-289
  {
    id: 102,
    name: "Low Sensitivity - Lower Brands DE",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "19.05.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "20.05.2023",
    endedOn: "18.06.2023",
    significance: 96,
    lift: 2.3,
  },
  {
    id: 147,
    name: "BVDF Restaurants + SF Elasticity",
    status: "completed",
    type: "ab",
    targetGroups: 6,
    variations: 6,
    createdOn: "23.06.2023",
    createdBy: "bob.marley",
    email: "bob.marley@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "25.06.2023",
    endedOn: "25.07.2023",
    significance: 98,
    lift: 4.7,
  },
  {
    id: 218,
    name: "MOV Surge Test - Berlin Central",
    status: "completed",
    type: "switchback",
    targetGroups: 2,
    variations: 2,
    createdOn: "12.07.2023",
    createdBy: "stevie.wonder",
    email: "stevie.wonder@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "14.07.2023",
    endedOn: "14.08.2023",
    significance: 95,
    lift: -1.2,
  },
  {
    id: 289,
    name: "Dummy - BVDF Restaurants Test",
    status: "draft",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "25.07.2023",
    createdBy: "tupac.shakur",
    email: "tupac.shakur@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
  },
  // August-September 2023 - IDs: 341-512
  {
    id: 341,
    name: "DE_Berlin_DF_Elasticity_McDonalds",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "02.08.2023",
    createdBy: "tupac.shakur",
    email: "tupac.shakur@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "05.08.2023",
    daysRunning: 267,
    significance: 94,
  },
  {
    id: 387,
    name: "FP_DE_DF_Distance_Tier_Test",
    status: "draft",
    type: "ab",
    targetGroups: 6,
    variations: 6,
    createdOn: "30.08.2023",
    createdBy: "nina.simone",
    email: "nina.simone@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
  },
  {
    id: 456,
    name: "FP_DE_MOV_Premium_Brands_Loyal",
    status: "running",
    type: "ab",
    targetGroups: 1,
    variations: 1,
    createdOn: "05.09.2023",
    createdBy: "freddie.mercury",
    email: "freddie.mercury@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "08.09.2023",
    daysRunning: 232,
    significance: 97,
  },
  {
    id: 512,
    name: "Hamburg DF + MOV Combined Test",
    status: "completed",
    type: "ab",
    targetGroups: 11,
    variations: 11,
    createdOn: "07.09.2023",
    createdBy: "aretha.franklin",
    email: "aretha.franklin@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "10.09.2023",
    endedOn: "10.11.2023",
    significance: 99,
    lift: 8.2,
  },
  // October-December 2023 - IDs: 634-891
  {
    id: 634,
    name: "FP_DE_Grocery_MOV_Optimization",
    status: "completed",
    type: "ab",
    targetGroups: 4,
    variations: 4,
    createdOn: "15.10.2023",
    createdBy: "tina.turner",
    email: "tina.turner@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "18.10.2023",
    endedOn: "18.12.2023",
    significance: 97,
    lift: 3.1,
  },
  {
    id: 678,
    name: "DE_Low_Sensitivity_QSR_Test",
    status: "draft",
    type: "ab",
    targetGroups: 1,
    variations: 1,
    createdOn: "18.10.2023",
    createdBy: "amy.winehouse",
    email: "amy.winehouse@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Test Elasticity",
    primaryMetric: "Order Volume",
  },
  {
    id: 745,
    name: "DE_Munich_KFC_MOV_Optimization",
    status: "draft",
    type: "ab",
    targetGroups: 7,
    variations: 7,
    createdOn: "14.11.2023",
    createdBy: "eric.clapton",
    email: "eric.clapton@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
  },
  {
    id: 823,
    name: "Weather Surge - Rainy Days Berlin",
    status: "completed",
    type: "switchback",
    targetGroups: 8,
    variations: 3,
    createdOn: "28.11.2023",
    createdBy: "elton.john",
    email: "elton.john@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "01.12.2023",
    endedOn: "01.02.2024",
    significance: 96,
    lift: 5.8,
  },
  {
    id: 891,
    name: "Starbucks MOV Elasticity - Munich",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 3,
    createdOn: "08.12.2023",
    createdBy: "prince.nelson",
    email: "prince.nelson@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "12.12.2023",
    endedOn: "12.02.2024",
    significance: 95,
    lift: -2.4,
  },
  // January-February 2024 - IDs: 1047-1892
  {
    id: 1047,
    name: "DE_Berlin_Burger_King_DF_15Jan",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 3,
    createdOn: "15.01.2024",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "18.01.2024",
    daysRunning: 101,
    significance: 89,
  },
  {
    id: 1124,
    name: "High Basket Value - SF Reduction",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 3,
    createdOn: "20.01.2024",
    createdBy: "lionel.richie",
    email: "lionel.richie@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Reduce Costs",
    primaryMetric: "Gross Profit",
    startedOn: "22.01.2024",
    endedOn: "22.03.2024",
    significance: 98,
    lift: 6.1,
  },
  {
    id: 1203,
    name: "FP_DE_High_Value_Orders_SF_Test",
    status: "running",
    type: "ab",
    targetGroups: 4,
    variations: 2,
    createdOn: "22.01.2024",
    createdBy: "madonna.ciccone",
    email: "madonna.ciccone@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "25.01.2024",
    daysRunning: 94,
    significance: 72,
  },
  {
    id: 1356,
    name: "DE_Peak_Hours_Surge_Pricing",
    status: "running",
    type: "switchback",
    targetGroups: 5,
    variations: 4,
    createdOn: "03.02.2024",
    createdBy: "whitney.houston",
    email: "whitney.houston@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "05.02.2024",
    daysRunning: 83,
    significance: 91,
  },
  {
    id: 1478,
    name: "DE_Hamburg_Pizza_Chains_BVDF",
    status: "draft",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "10.02.2024",
    createdBy: "michael.jackson",
    email: "michael.jackson@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
  },
  {
    id: 1563,
    name: "Munich Airport Zone Premium DF",
    status: "completed",
    type: "ab",
    targetGroups: 4,
    variations: 3,
    createdOn: "15.02.2024",
    createdBy: "george.michael",
    email: "george.michael@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "18.02.2024",
    endedOn: "18.04.2024",
    significance: 97,
    lift: 1.9,
  },
  {
    id: 1689,
    name: "Berlin Central Zone DF Tier Test",
    status: "running",
    type: "ab",
    targetGroups: 6,
    variations: 3,
    createdOn: "18.02.2024",
    createdBy: "james.brown",
    email: "james.brown@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "20.02.2024",
    daysRunning: 68,
    significance: 85,
  },
  {
    id: 1892,
    name: "Subway + Dominos DF Combined",
    status: "draft",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "25.02.2024",
    createdBy: "diana.ross",
    email: "diana.ross@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Revenue per Order",
  },
  // March-April 2024 - IDs: 2034-4712
  {
    id: 2034,
    name: "DE_Late_Night_Premium_Pricing",
    status: "running",
    type: "switchback",
    targetGroups: 3,
    variations: 2,
    createdOn: "01.03.2024",
    createdBy: "stevie.nicks",
    email: "stevie.nicks@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "04.03.2024",
    daysRunning: 56,
    significance: 78,
  },
  {
    id: 2178,
    name: "DE_Frankfurt_New_Market_DF",
    status: "draft",
    type: "ab",
    targetGroups: 4,
    variations: 3,
    createdOn: "05.03.2024",
    createdBy: "mick.jagger",
    email: "mick.jagger@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
  },
  {
    id: 2456,
    name: "FP_DE_Mitte_Lunch_Rush_Test",
    status: "running",
    type: "ab",
    targetGroups: 5,
    variations: 2,
    createdOn: "12.03.2024",
    createdBy: "cher.sarkisian",
    email: "cher.sarkisian@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Order Volume",
    startedOn: "15.03.2024",
    daysRunning: 45,
    significance: 62,
  },
  {
    id: 2789,
    name: "DE_Weekend_Brunch_Elasticity",
    status: "completed",
    type: "ab",
    targetGroups: 7,
    variations: 4,
    createdOn: "18.03.2024",
    createdBy: "celine.dion",
    email: "celine.dion@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "20.03.2024",
    endedOn: "20.04.2024",
    significance: 96,
    lift: 3.7,
  },
  {
    id: 3124,
    name: "DE_Cologne_QSR_MOV_8EUR_Test",
    status: "draft",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "25.03.2024",
    createdBy: "phil.collins",
    email: "phil.collins@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
  },
  {
    id: 3567,
    name: "FP_DE_New_User_DF_Waiver",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "01.04.2024",
    createdBy: "janet.jackson",
    email: "janet.jackson@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "03.04.2024",
    daysRunning: 26,
    significance: 48,
  },
  {
    id: 3891,
    name: "DE_Residential_vs_Commercial_SF",
    status: "draft",
    type: "switchback",
    targetGroups: 6,
    variations: 2,
    createdOn: "08.04.2024",
    createdBy: "cyndi.lauper",
    email: "cyndi.lauper@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Test Elasticity",
    primaryMetric: "Gross Profit",
  },
  {
    id: 4234,
    name: "Healthy Food Vertical - MOV Test",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 3,
    createdOn: "15.04.2024",
    createdBy: "bruce.springsteen",
    email: "bruce.springsteen@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "18.04.2024",
    daysRunning: 11,
    significance: 34,
  },
  {
    id: 4712,
    name: "FP_DE_Loyalty_Tier_DF_Discount",
    status: "draft",
    type: "ab",
    targetGroups: 4,
    variations: 4,
    createdOn: "22.04.2024",
    createdBy: "barbra.streisand",
    email: "barbra.streisand@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
  },
];

// Pricing components for dropdowns
export const pricingComponents: PricingComponent[] = [
  {
    id: "df_london_258",
    name: "McDonalds - London - 2,5,8",
    type: "delivery_fee",
    value: "Distance based: 2€, 5€, 8€",
    description: "Distance-based delivery fee for McDonalds in London area",
  },
  {
    id: "mov_london_12",
    name: "McDonalds - London - 12",
    type: "minimum_order_value",
    value: "12€",
    description: "Minimum order value of 12€",
  },
  {
    id: "mov_london_11",
    name: "McDonalds - London - 11",
    type: "minimum_order_value",
    value: "11€",
    description: "Minimum order value of 11€",
  },
  {
    id: "mov_london_10",
    name: "McDonalds - London - 10",
    type: "minimum_order_value",
    value: "10€",
    description: "Minimum order value of 10€",
  },
  {
    id: "sf_central_london",
    name: "central-london-sf",
    type: "service_fee",
    value: "2% of basket value",
    description: "Service fee for central London area",
  },
  {
    id: "sf_greater_london",
    name: "greater-london-sf",
    type: "service_fee",
    value: "1.5% of basket value",
    description: "Service fee for greater London area",
  },
];

// Automatic assignments for import dropdown
export const automaticAssignments = [
  {
    id: "aa_mcdonalds_berlin",
    name: "McDonalds Berlin - Standard Pricing",
    targetGroups: 3,
    description: "Standard pricing for all McDonalds in Berlin",
  },
  {
    id: "aa_mcdonalds_london",
    name: "McDonalds London - Premium Pricing",
    targetGroups: 2,
    description: "Premium pricing for McDonalds in central London",
  },
  {
    id: "aa_kfc_germany",
    name: "KFC Germany - National Pricing",
    targetGroups: 5,
    description: "National pricing scheme for KFC across Germany",
  },
  {
    id: "aa_burger_king_uk",
    name: "Burger King UK - Regional Pricing",
    targetGroups: 4,
    description: "Regional pricing variations for Burger King UK",
  },
];

// Sample target group for experiment form
export const sampleTargetGroup: TargetGroup = {
  id: "tg_1",
  priority: 1,
  vendorFilters: [
    {
      id: "vf_1",
      field: "Chain Name",
      clause: "is",
      values: ["McDonalds"],
    },
  ],
  conditions: [],
  components: [
    {
      type: "Delivery Fee",
      control: "McDonalds - London - 2,5,8",
      variations: [
        { id: "v1", name: "Variation 1", value: "Same as Control", isSameAsControl: true },
        { id: "v2", name: "Variation 2", value: "Same as Control", isSameAsControl: true },
      ],
    },
    {
      type: "Minimum Order Value",
      control: "McDonalds - London - 12",
      variations: [
        { id: "v1", name: "Variation 1", value: "McDonalds - London - 11", isSameAsControl: false },
        { id: "v2", name: "Variation 2", value: "McDonalds - London - 10", isSameAsControl: false },
      ],
    },
    {
      type: "Service Fee",
      control: "central-london-sf",
      variations: [
        { id: "v1", name: "Variation 1", value: "Same as Control", isSameAsControl: true },
        { id: "v2", name: "Variation 2", value: "Same as Control", isSameAsControl: true },
      ],
    },
  ],
};

// Vendor filter field options
export const vendorFilterFields = [
  { value: "chain_name", label: "Chain Name" },
  { value: "vendor_id", label: "Vendor ID" },
  { value: "zone", label: "Zone" },
  { value: "city", label: "City" },
  { value: "vertical", label: "Vertical" },
  { value: "cuisine", label: "Cuisine" },
];

// Clause options for vendor filters
export const clauseOptions = [
  { value: "is", label: "is" },
  { value: "is_not", label: "is not" },
  { value: "contains", label: "contains" },
  { value: "starts_with", label: "starts with" },
];
