// Mock data for DPS Dashboard prototype

import type {
  Experiment,
  Campaign,
  KPIMetric,
  PricingComponent,
  TargetGroup,
} from "./types";

// Daily Orders Trend Data (last 30 days)
export const dailyOrdersData = [
  { date: "Mar 28", orders: 1850, deliveryFee: 2.15, gmv: 5920 },
  { date: "Mar 29", orders: 1920, deliveryFee: 2.18, gmv: 6150 },
  { date: "Mar 30", orders: 2100, deliveryFee: 2.22, gmv: 6720 },
  { date: "Mar 31", orders: 2250, deliveryFee: 2.20, gmv: 7200 },
  { date: "Apr 1", orders: 1980, deliveryFee: 2.19, gmv: 6340 },
  { date: "Apr 2", orders: 1890, deliveryFee: 2.21, gmv: 6050 },
  { date: "Apr 3", orders: 1950, deliveryFee: 2.23, gmv: 6240 },
  { date: "Apr 4", orders: 2050, deliveryFee: 2.18, gmv: 6560 },
  { date: "Apr 5", orders: 2180, deliveryFee: 2.20, gmv: 6980 },
  { date: "Apr 6", orders: 2320, deliveryFee: 2.24, gmv: 7420 },
  { date: "Apr 7", orders: 2450, deliveryFee: 2.26, gmv: 7840 },
  { date: "Apr 8", orders: 2100, deliveryFee: 2.22, gmv: 6720 },
  { date: "Apr 9", orders: 1980, deliveryFee: 2.25, gmv: 6340 },
  { date: "Apr 10", orders: 2050, deliveryFee: 2.24, gmv: 6560 },
  { date: "Apr 11", orders: 2150, deliveryFee: 2.23, gmv: 6880 },
  { date: "Apr 12", orders: 2280, deliveryFee: 2.26, gmv: 7300 },
  { date: "Apr 13", orders: 2400, deliveryFee: 2.28, gmv: 7680 },
  { date: "Apr 14", orders: 2520, deliveryFee: 2.30, gmv: 8060 },
  { date: "Apr 15", orders: 2180, deliveryFee: 2.25, gmv: 6980 },
  { date: "Apr 16", orders: 2050, deliveryFee: 2.24, gmv: 6560 },
  { date: "Apr 17", orders: 2120, deliveryFee: 2.26, gmv: 6780 },
  { date: "Apr 18", orders: 2200, deliveryFee: 2.25, gmv: 7040 },
  { date: "Apr 19", orders: 2350, deliveryFee: 2.27, gmv: 7520 },
  { date: "Apr 20", orders: 2480, deliveryFee: 2.29, gmv: 7940 },
  { date: "Apr 21", orders: 2600, deliveryFee: 2.31, gmv: 8320 },
  { date: "Apr 22", orders: 2250, deliveryFee: 2.26, gmv: 7200 },
  { date: "Apr 23", orders: 2100, deliveryFee: 2.24, gmv: 6720 },
  { date: "Apr 24", orders: 2180, deliveryFee: 2.25, gmv: 6980 },
  { date: "Apr 25", orders: 2280, deliveryFee: 2.26, gmv: 7300 },
  { date: "Apr 26", orders: 2154, deliveryFee: 2.26, gmv: 6893 },
];

// City Performance Data
export const cityPerformanceData = [
  { city: "Berlin", orders: 18420, avgDeliveryFee: 2.45, cvr: 62.3, gmv: 58940 },
  { city: "Hamburg", orders: 12850, avgDeliveryFee: 2.32, cvr: 59.8, gmv: 41120 },
  { city: "Munich", orders: 14200, avgDeliveryFee: 2.58, cvr: 64.1, gmv: 45440 },
  { city: "Cologne", orders: 8450, avgDeliveryFee: 2.18, cvr: 57.2, gmv: 27040 },
  { city: "Frankfurt", orders: 8234, avgDeliveryFee: 2.35, cvr: 60.5, gmv: 26349 },
  { city: "Stuttgart", orders: 6820, avgDeliveryFee: 2.28, cvr: 58.4, gmv: 21824 },
  { city: "Düsseldorf", orders: 5940, avgDeliveryFee: 2.22, cvr: 56.9, gmv: 19008 },
  { city: "Leipzig", orders: 4560, avgDeliveryFee: 2.12, cvr: 55.2, gmv: 14592 },
];

// Vertical Breakdown Data
export const verticalBreakdownData = [
  { name: "Restaurants", value: 42, orders: 26105, color: "#6366f1" },
  { name: "Grocery", value: 28, orders: 17403, color: "#22c55e" },
  { name: "Convenience", value: 15, orders: 9323, color: "#f59e0b" },
  { name: "Pharmacy", value: 8, orders: 4972, color: "#ec4899" },
  { name: "Flowers", value: 4, orders: 2486, color: "#8b5cf6" },
  { name: "Other", value: 3, orders: 1865, color: "#94a3b8" },
];

// Delivery Fee Distribution by Range
export const deliveryFeeDistribution = [
  { range: "€0-1", count: 4850, percentage: 7.8 },
  { range: "€1-2", count: 18920, percentage: 30.4 },
  { range: "€2-3", count: 24680, percentage: 39.7 },
  { range: "€3-4", count: 10250, percentage: 16.5 },
  { range: "€4+", count: 3454, percentage: 5.6 },
];

// KPI Metrics for Dashboard
export const kpiMetrics: KPIMetric[] = [
  {
    id: "delivery_fee",
    label: "Average Delivery Fee",
    value: 2.26,
    change: 0.48,
    changeType: "positive",
    prefix: "EUR",
    format: "currency",
  },
  {
    id: "total_orders",
    label: "Total Orders",
    value: 62154,
    change: -2.2,
    changeType: "negative",
    format: "number",
  },
  {
    id: "gmv",
    label: "Gross Merchandise Value",
    value: 200638,
    change: 0.48,
    changeType: "positive",
    prefix: "EUR",
    format: "currency_whole",
  },
  {
    id: "afv",
    label: "Average Food Value",
    value: 14.06,
    change: -0.06,
    changeType: "negative",
    prefix: "EUR",
    format: "currency",
  },
  {
    id: "cvr",
    label: "Conversion Rate",
    value: 60.81,
    change: 1.32,
    changeType: "positive",
    suffix: "%",
    format: "percentage",
  },
];

// Active Experiments for Dashboard
export const activeExperiments: {
  id: string;
  name: string;
  activeDuration: string;
  significance: string;
}[] = [
  {
    id: "AR_20240406_R_B0_O_ElasticityCaba",
    name: "AR_20240406_R_B0_O_ElasticityCaba",
    activeDuration: "28 days",
    significance: "25%",
  },
  {
    id: "AR_20240405_L_D0_P_MOVKiosks",
    name: "AR_20240405_L_D0_P_MOVKiosks",
    activeDuration: "16 days",
    significance: "25%",
  },
  {
    id: "AR_20240306_D_G0_O_BV_SanMiguel",
    name: "AR_20240306_D_G0_O_BV_SanMiguel",
    activeDuration: "9 days",
    significance: "25%",
  },
  {
    id: "CL_20240131_Z_Z0_O_SBF_Tucuman",
    name: "CL_20240131_Z_Z0_O_SBF_Tucuman",
    activeDuration: "5 days",
    significance: "25%",
  },
];

// Active Campaigns for Dashboard
export const activeCampaigns: Campaign[] = [
  {
    id: "PY_DFS0_MOV3499_DRINKS_DMT",
    name: "PY - DFS0/MOV3499 - DRINKS DMT",
    timeLeft: "28 days",
    budgetLeft: "3%",
    status: "active",
  },
  {
    id: "PY_DFS0_MOV2499_ESPECIAL_FIESTAS",
    name: "PY - DFS0/MOV2499 - ESPECIAL FIESTAS",
    timeLeft: "16 days",
    budgetLeft: null,
    status: "active",
  },
  {
    id: "PY_DFS0_DBMOV1299_2499_SBX",
    name: "PY - DFS0/DBMOV1299 a 2499 - SBX",
    timeLeft: "9 days",
    budgetLeft: "28%",
    status: "active",
  },
  {
    id: "PY_DFS0_DBMOV1499_1999_REST_AMBA",
    name: "PY - DFS0/DBMOV1499 a 1999 - REST AMBA",
    timeLeft: "5 days",
    budgetLeft: null,
    status: "active",
  },
];

// Experiments list for Experiments page
// IDs correlate with creation date (higher ID = more recent)
// 8 owners with unequal output (rekha: 8, carlos: 7, sarah: 6, david: 5, nina: 4, mike: 3, lisa: 2, jan: 1)
// Realistic distribution: 17 completed, 13 running, 6 draft
export const experiments: Experiment[] = [
  // === May–July 2023 (oldest) ===
  {
    id: 102,
    name: "Low Sensitivity - Lower Brands DE",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "19.05.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "20.05.2023",
    endedOn: "18.06.2023",
    significance: 96,
    lift: 2.3,
  },
  {
    id: 147,
    name: "BVDF Restaurants + SF Elasticity",
    status: "completed",
    type: "ab",
    targetGroups: 42,
    variations: 6,
    createdOn: "23.06.2023",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "25.06.2023",
    endedOn: "25.07.2023",
    significance: 98,
    lift: 4.7,
  },
  {
    id: 218,
    name: "MOV Surge Test - Berlin Central",
    status: "completed",
    type: "switchback",
    targetGroups: 2,
    variations: 2,
    createdOn: "12.07.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "14.07.2023",
    endedOn: "14.08.2023",
    significance: 91,
    lift: -1.2,
  },
  {
    id: 267,
    name: "Hamburg DF Tier - QSR Chains",
    status: "completed",
    type: "ab",
    targetGroups: 3,
    variations: 3,
    createdOn: "20.07.2023",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "22.07.2023",
    endedOn: "22.08.2023",
    significance: 97,
    lift: -2.8,
  },
  {
    id: 312,
    name: "Dummy - BVDF Restaurants Test",
    status: "draft",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "25.07.2023",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
  },
  // === August–September 2023 ===
  {
    id: 341,
    name: "DE_Berlin_DF_Elasticity_McDonalds",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "02.08.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "05.08.2023",
    daysRunning: 267,
    significance: 94,
  },
  {
    id: 387,
    name: "FP_DE_DF_Distance_Tier_Test",
    status: "completed",
    type: "ab",
    targetGroups: 56,
    variations: 6,
    createdOn: "30.08.2023",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "02.09.2023",
    endedOn: "02.11.2023",
    significance: 99,
    lift: 6.4,
  },
  {
    id: 423,
    name: "FP_DE_MOV_Premium_Brands_Loyal",
    status: "completed",
    type: "ab",
    targetGroups: 1,
    variations: 1,
    createdOn: "05.09.2023",
    createdBy: "nina.simone",
    email: "nina.simone@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "08.09.2023",
    endedOn: "08.11.2023",
    significance: 97,
    lift: 1.4,
  },
  {
    id: 478,
    name: "Hamburg DF + MOV Combined Test",
    status: "completed",
    type: "ab",
    targetGroups: 38,
    variations: 11,
    createdOn: "07.09.2023",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "10.09.2023",
    endedOn: "10.11.2023",
    significance: 99,
    lift: 8.2,
  },
  {
    id: 512,
    name: "Berlin Grocery MOV - Weekend Rush",
    status: "completed",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "15.09.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "18.09.2023",
    endedOn: "18.11.2023",
    significance: 87,
    lift: -0.4,
  },
  {
    id: 589,
    name: "DE_Munich_New_User_DF_Waiver",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "28.09.2023",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "01.10.2023",
    endedOn: "01.12.2023",
    significance: 96,
    lift: 3.9,
  },
  // === October–December 2023 ===
  {
    id: 634,
    name: "FP_DE_Grocery_MOV_Optimization",
    status: "completed",
    type: "ab",
    targetGroups: 18,
    variations: 4,
    createdOn: "15.10.2023",
    createdBy: "mike.torres",
    email: "mike.torres@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "18.10.2023",
    endedOn: "18.12.2023",
    significance: 97,
    lift: 3.1,
  },
  {
    id: 678,
    name: "DE_Low_Sensitivity_QSR_Test",
    status: "draft",
    type: "ab",
    targetGroups: 1,
    variations: 1,
    createdOn: "18.10.2023",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Test Elasticity",
    primaryMetric: "Order Volume",
  },
  {
    id: 723,
    name: "Hamburg Grocery Late Night Pricing",
    status: "completed",
    type: "switchback",
    targetGroups: 2,
    variations: 2,
    createdOn: "02.11.2023",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "05.11.2023",
    endedOn: "05.01.2024",
    significance: 93,
    lift: -0.7,
  },
  {
    id: 745,
    name: "DE_Munich_KFC_MOV_Optimization",
    status: "running",
    type: "ab",
    targetGroups: 24,
    variations: 7,
    createdOn: "14.11.2023",
    createdBy: "nina.simone",
    email: "nina.simone@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "17.11.2023",
    daysRunning: 164,
    significance: 89,
  },
  {
    id: 823,
    name: "Weather Surge - Rainy Days Berlin",
    status: "completed",
    type: "switchback",
    targetGroups: 52,
    variations: 3,
    createdOn: "28.11.2023",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "01.12.2023",
    endedOn: "01.02.2024",
    significance: 96,
    lift: 5.8,
  },
  {
    id: 891,
    name: "Starbucks MOV Elasticity - Munich",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 3,
    createdOn: "08.12.2023",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "12.12.2023",
    endedOn: "12.02.2024",
    significance: 95,
    lift: -2.4,
  },
  {
    id: 945,
    name: "Cologne Weekend Brunch DF Test",
    status: "completed",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "18.12.2023",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Reduce Costs",
    primaryMetric: "Gross Profit",
    startedOn: "20.12.2023",
    endedOn: "20.02.2024",
    significance: 85,
    lift: -3.6,
  },
  // === January–February 2024 ===
  {
    id: 1047,
    name: "DE_Berlin_Burger_King_DF_15Jan",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 3,
    createdOn: "15.01.2024",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "18.01.2024",
    daysRunning: 101,
    significance: 78,
  },
  {
    id: 1124,
    name: "High Basket Value - SF Reduction",
    status: "completed",
    type: "ab",
    targetGroups: 2,
    variations: 3,
    createdOn: "20.01.2024",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Reduce Costs",
    primaryMetric: "Gross Profit",
    startedOn: "22.01.2024",
    endedOn: "22.03.2024",
    significance: 98,
    lift: 6.1,
  },
  {
    id: 1203,
    name: "FP_DE_High_Value_Orders_SF_Test",
    status: "running",
    type: "ab",
    targetGroups: 33,
    variations: 2,
    createdOn: "22.01.2024",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "25.01.2024",
    daysRunning: 94,
    significance: 72,
  },
  {
    id: 1289,
    name: "Munich Grocery Express MOV Test",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "28.01.2024",
    createdBy: "nina.simone",
    email: "nina.simone@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "01.02.2024",
    daysRunning: 87,
    significance: 84,
  },
  {
    id: 1356,
    name: "DE_Peak_Hours_Surge_Pricing",
    status: "running",
    type: "switchback",
    targetGroups: 14,
    variations: 4,
    createdOn: "03.02.2024",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "05.02.2024",
    daysRunning: 83,
    significance: 91,
  },
  {
    id: 1478,
    name: "Frankfurt QSR Chains - DF Tiers",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "10.02.2024",
    createdBy: "mike.torres",
    email: "mike.torres@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "13.02.2024",
    daysRunning: 75,
    significance: 68,
  },
  {
    id: 1563,
    name: "Hamburg Airport Zone Premium DF",
    status: "completed",
    type: "ab",
    targetGroups: 47,
    variations: 3,
    createdOn: "15.02.2024",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Increase CVR",
    primaryMetric: "Order Volume",
    startedOn: "18.02.2024",
    endedOn: "18.04.2024",
    significance: 97,
    lift: 1.9,
  },
  {
    id: 1689,
    name: "Berlin Central Zone DF Tier Test",
    status: "running",
    type: "switchback",
    targetGroups: 12,
    variations: 3,
    createdOn: "18.02.2024",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "20.02.2024",
    daysRunning: 68,
    significance: 55,
  },
  {
    id: 1756,
    name: "Munich Premium Loyalty DF Discount",
    status: "draft",
    type: "ab",
    targetGroups: 16,
    variations: 4,
    createdOn: "22.02.2024",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
  },
  {
    id: 1892,
    name: "Subway + Dominos DF Combined",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "25.02.2024",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Test Elasticity",
    primaryMetric: "Revenue per Order",
    startedOn: "28.02.2024",
    daysRunning: 60,
    significance: 62,
  },
  // === March–April 2024 ===
  {
    id: 2034,
    name: "DE_Late_Night_Premium_Pricing",
    status: "running",
    type: "switchback",
    targetGroups: 3,
    variations: 2,
    createdOn: "01.03.2024",
    createdBy: "carlos.mendez",
    email: "carlos.mendez@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Gross Profit",
    startedOn: "04.03.2024",
    daysRunning: 56,
    significance: 42,
  },
  {
    id: 2178,
    name: "DE_Frankfurt_New_Market_DF",
    status: "draft",
    type: "ab",
    targetGroups: 22,
    variations: 3,
    createdOn: "05.03.2024",
    createdBy: "mike.torres",
    email: "mike.torres@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
  },
  {
    id: 2345,
    name: "Munich Convenience Store MOV Test",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "10.03.2024",
    createdBy: "nina.simone",
    email: "nina.simone@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
    startedOn: "13.03.2024",
    daysRunning: 47,
    significance: 38,
  },
  {
    id: 2456,
    name: "FP_DE_Mitte_Lunch_Rush_Test",
    status: "running",
    type: "ab",
    targetGroups: 61,
    variations: 2,
    createdOn: "12.03.2024",
    createdBy: "david.bowie",
    email: "david.bowie@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Optimize Pricing",
    primaryMetric: "Order Volume",
    startedOn: "15.03.2024",
    daysRunning: 45,
    significance: 51,
  },
  {
    id: 2789,
    name: "DE_Weekend_Brunch_Elasticity",
    status: "completed",
    type: "ab",
    targetGroups: 29,
    variations: 4,
    createdOn: "18.03.2024",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Munich",
    objective: "Test Elasticity",
    primaryMetric: "Conversion Rate",
    startedOn: "20.03.2024",
    endedOn: "20.04.2024",
    significance: 96,
    lift: 3.7,
  },
  {
    id: 3124,
    name: "DE_Cologne_QSR_MOV_8EUR_Test",
    status: "draft",
    type: "ab",
    targetGroups: 3,
    variations: 2,
    createdOn: "25.03.2024",
    createdBy: "lisa.kumar",
    email: "lisa.kumar@deliveryhero.com",
    region: "Germany",
    city: "Cologne",
    objective: "Optimize Pricing",
    primaryMetric: "Avg Delivery Fee",
  },
  {
    id: 3567,
    name: "FP_DE_New_User_DF_Waiver",
    status: "running",
    type: "ab",
    targetGroups: 2,
    variations: 2,
    createdOn: "01.04.2024",
    createdBy: "lisa.kumar",
    email: "lisa.kumar@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "03.04.2024",
    daysRunning: 26,
    significance: 28,
  },
  {
    id: 3891,
    name: "DE_Residential_vs_Commercial_SF",
    status: "draft",
    type: "switchback",
    targetGroups: 45,
    variations: 2,
    createdOn: "08.04.2024",
    createdBy: "jan.mueller",
    email: "jan.mueller@deliveryhero.com",
    region: "Germany",
    city: "Frankfurt",
    objective: "Test Elasticity",
    primaryMetric: "Gross Profit",
  },
  {
    id: 4234,
    name: "Healthy Food Vertical - MOV Test",
    status: "running",
    type: "ab",
    targetGroups: 3,
    variations: 3,
    createdOn: "15.04.2024",
    createdBy: "sarah.chen",
    email: "sarah.chen@deliveryhero.com",
    region: "Germany",
    city: "Hamburg",
    objective: "Optimize Pricing",
    primaryMetric: "Revenue per Order",
    startedOn: "18.04.2024",
    daysRunning: 11,
    significance: 15,
  },
  {
    id: 4712,
    name: "FP_DE_Loyalty_Tier_DF_Discount",
    status: "running",
    type: "ab",
    targetGroups: 35,
    variations: 4,
    createdOn: "22.04.2024",
    createdBy: "rekha.bhardwaj",
    email: "rekha.bhardwaj@deliveryhero.com",
    region: "Germany",
    city: "Berlin",
    objective: "Increase CVR",
    primaryMetric: "Conversion Rate",
    startedOn: "25.04.2024",
    daysRunning: 4,
    significance: 8,
  },
];

// Pricing components for dropdowns
export const pricingComponents: PricingComponent[] = [
  {
    id: "df_london_258",
    name: "McDonalds - London - 2,5,8",
    type: "delivery_fee",
    value: "Distance based: 2€, 5€, 8€",
    description: "Distance-based delivery fee for McDonalds in London area",
  },
  {
    id: "mov_london_12",
    name: "McDonalds - London - 12",
    type: "minimum_order_value",
    value: "12€",
    description: "Minimum order value of 12€",
  },
  {
    id: "mov_london_11",
    name: "McDonalds - London - 11",
    type: "minimum_order_value",
    value: "11€",
    description: "Minimum order value of 11€",
  },
  {
    id: "mov_london_10",
    name: "McDonalds - London - 10",
    type: "minimum_order_value",
    value: "10€",
    description: "Minimum order value of 10€",
  },
  {
    id: "sf_central_london",
    name: "central-london-sf",
    type: "service_fee",
    value: "2% of basket value",
    description: "Service fee for central London area",
  },
  {
    id: "sf_greater_london",
    name: "greater-london-sf",
    type: "service_fee",
    value: "1.5% of basket value",
    description: "Service fee for greater London area",
  },
];

// Automatic assignments for import dropdown
export const automaticAssignments = [
  {
    id: "aa_mcdonalds_berlin",
    name: "McDonalds Berlin - Standard Pricing",
    targetGroups: 3,
    description: "Standard pricing for all McDonalds in Berlin",
  },
  {
    id: "aa_mcdonalds_london",
    name: "McDonalds London - Premium Pricing",
    targetGroups: 2,
    description: "Premium pricing for McDonalds in central London",
  },
  {
    id: "aa_kfc_germany",
    name: "KFC Germany - National Pricing",
    targetGroups: 5,
    description: "National pricing scheme for KFC across Germany",
  },
  {
    id: "aa_burger_king_uk",
    name: "Burger King UK - Regional Pricing",
    targetGroups: 4,
    description: "Regional pricing variations for Burger King UK",
  },
];

// Sample target group for experiment form
export const sampleTargetGroup: TargetGroup = {
  id: "tg_1",
  priority: 1,
  vendorFilters: [
    {
      id: "vf_1",
      field: "Chain Name",
      clause: "is",
      values: ["McDonalds"],
    },
  ],
  conditions: [],
  components: [
    {
      type: "Delivery Fee",
      control: "McDonalds - London - 2,5,8",
      variations: [
        { id: "v1", name: "Variation 1", value: "Same as Control", isSameAsControl: true },
        { id: "v2", name: "Variation 2", value: "Same as Control", isSameAsControl: true },
      ],
    },
    {
      type: "Minimum Order Value",
      control: "McDonalds - London - 12",
      variations: [
        { id: "v1", name: "Variation 1", value: "McDonalds - London - 11", isSameAsControl: false },
        { id: "v2", name: "Variation 2", value: "McDonalds - London - 10", isSameAsControl: false },
      ],
    },
    {
      type: "Service Fee",
      control: "central-london-sf",
      variations: [
        { id: "v1", name: "Variation 1", value: "Same as Control", isSameAsControl: true },
        { id: "v2", name: "Variation 2", value: "Same as Control", isSameAsControl: true },
      ],
    },
  ],
};

// Vendor filter field options
export const vendorFilterFields = [
  { value: "chain_name", label: "Chain Name" },
  { value: "vendor_id", label: "Vendor ID" },
  { value: "zone", label: "Zone" },
  { value: "city", label: "City" },
  { value: "vertical", label: "Vertical" },
  { value: "cuisine", label: "Cuisine" },
];

// Clause options for vendor filters
export const clauseOptions = [
  { value: "is", label: "is" },
  { value: "is_not", label: "is not" },
  { value: "contains", label: "contains" },
  { value: "starts_with", label: "starts with" },
];
